name: dart_glfw
description: Dart bindings for the GLFW windowing library
version: 0.2.1
repository: https://github.com/gliscowo/dart_glfw

publish_to: https://pub.wispforest.io

environment:
  sdk: ^3.0.5

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  ffigen: ^16.1.0
  lints: ^5.1.1
  test: ^1.21.0
