// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:dart_glfw/glfw')
library;

import 'dart:ffi' as ffi;

/// Initializes the GLFW library.
@ffi.Native<ffi.Int Function()>()
external int glfwInit();

/// Terminates the GLFW library.
@ffi.Native<ffi.Void Function()>()
external void glfwTerminate();

/// Sets the specified init hint to the desired value.
@ffi.Native<ffi.Void Function(ffi.Int, ffi.Int)>()
external void glfwInitHint(int hint, int value);

/// Sets the init allocator to the desired value.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWallocator>)>()
external void glfwInitAllocator(ffi.Pointer<GLFWallocator> allocator);

/// Retrieves the version of the GLFW library.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external void glfwGetVersion(ffi.Pointer<ffi.Int> major, ffi.Pointer<ffi.Int> minor, ffi.Pointer<ffi.Int> rev);

/// Returns a string describing the compile-time configuration.
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> glfwGetVersionString();

/// Returns and clears the last error for the calling thread.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external int glfwGetError(ffi.Pointer<ffi.Pointer<ffi.Char>> description);

/// Sets the error callback.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int error_code, ffi.Pointer<ffi.Char> description)>> Function(
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int error_code, ffi.Pointer<ffi.Char> description)>>,
  )
>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int error_code, ffi.Pointer<ffi.Char> description)>>
glfwSetErrorCallback(
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int error_code, ffi.Pointer<ffi.Char> description)>> callback,
);

/// Returns the currently selected platform.
@ffi.Native<ffi.Int Function()>()
external int glfwGetPlatform();

/// Returns whether the library includes support for the specified platform.
@ffi.Native<ffi.Int Function(ffi.Int)>()
external int glfwPlatformSupported(int platform);

/// Returns the currently connected monitors.
@ffi.Native<ffi.Pointer<ffi.Pointer<GLFWmonitor>> Function(ffi.Pointer<ffi.Int>)>()
external ffi.Pointer<ffi.Pointer<GLFWmonitor>> glfwGetMonitors(ffi.Pointer<ffi.Int> count);

/// Returns the primary monitor.
@ffi.Native<ffi.Pointer<GLFWmonitor> Function()>()
external ffi.Pointer<GLFWmonitor> glfwGetPrimaryMonitor();

/// Returns the position of the monitor's viewport on the virtual screen.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWmonitor>, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external void glfwGetMonitorPos(ffi.Pointer<GLFWmonitor> monitor, ffi.Pointer<ffi.Int> xpos, ffi.Pointer<ffi.Int> ypos);

/// Retrieves the work area of the monitor.
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<GLFWmonitor>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
  )
>()
external void glfwGetMonitorWorkarea(
  ffi.Pointer<GLFWmonitor> monitor,
  ffi.Pointer<ffi.Int> xpos,
  ffi.Pointer<ffi.Int> ypos,
  ffi.Pointer<ffi.Int> width,
  ffi.Pointer<ffi.Int> height,
);

/// Returns the physical size of the monitor.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWmonitor>, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external void glfwGetMonitorPhysicalSize(
  ffi.Pointer<GLFWmonitor> monitor,
  ffi.Pointer<ffi.Int> widthMM,
  ffi.Pointer<ffi.Int> heightMM,
);

/// Retrieves the content scale for the specified monitor.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWmonitor>, ffi.Pointer<ffi.Float>, ffi.Pointer<ffi.Float>)>()
external void glfwGetMonitorContentScale(
  ffi.Pointer<GLFWmonitor> monitor,
  ffi.Pointer<ffi.Float> xscale,
  ffi.Pointer<ffi.Float> yscale,
);

/// Returns the name of the specified monitor.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<GLFWmonitor>)>()
external ffi.Pointer<ffi.Char> glfwGetMonitorName(ffi.Pointer<GLFWmonitor> monitor);

/// Sets the user pointer of the specified monitor.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWmonitor>, ffi.Pointer<ffi.Void>)>()
external void glfwSetMonitorUserPointer(ffi.Pointer<GLFWmonitor> monitor, ffi.Pointer<ffi.Void> pointer);

/// Returns the user pointer of the specified monitor.
@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<GLFWmonitor>)>()
external ffi.Pointer<ffi.Void> glfwGetMonitorUserPointer(ffi.Pointer<GLFWmonitor> monitor);

/// Sets the monitor configuration callback.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWmonitor> monitor, ffi.Int event)>> Function(
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWmonitor> monitor, ffi.Int event)>>,
  )
>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWmonitor> monitor, ffi.Int event)>>
glfwSetMonitorCallback(
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWmonitor> monitor, ffi.Int event)>> callback,
);

/// Returns the available video modes for the specified monitor.
@ffi.Native<ffi.Pointer<GLFWvidmode> Function(ffi.Pointer<GLFWmonitor>, ffi.Pointer<ffi.Int>)>()
external ffi.Pointer<GLFWvidmode> glfwGetVideoModes(ffi.Pointer<GLFWmonitor> monitor, ffi.Pointer<ffi.Int> count);

/// Returns the current mode of the specified monitor.
@ffi.Native<ffi.Pointer<GLFWvidmode> Function(ffi.Pointer<GLFWmonitor>)>()
external ffi.Pointer<GLFWvidmode> glfwGetVideoMode(ffi.Pointer<GLFWmonitor> monitor);

/// Generates a gamma ramp and sets it for the specified monitor.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWmonitor>, ffi.Float)>()
external void glfwSetGamma(ffi.Pointer<GLFWmonitor> monitor, double gamma);

/// Returns the current gamma ramp for the specified monitor.
@ffi.Native<ffi.Pointer<GLFWgammaramp> Function(ffi.Pointer<GLFWmonitor>)>()
external ffi.Pointer<GLFWgammaramp> glfwGetGammaRamp(ffi.Pointer<GLFWmonitor> monitor);

/// Sets the current gamma ramp for the specified monitor.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWmonitor>, ffi.Pointer<GLFWgammaramp>)>()
external void glfwSetGammaRamp(ffi.Pointer<GLFWmonitor> monitor, ffi.Pointer<GLFWgammaramp> ramp);

/// Resets all window hints to their default values.
@ffi.Native<ffi.Void Function()>()
external void glfwDefaultWindowHints();

/// Sets the specified window hint to the desired value.
@ffi.Native<ffi.Void Function(ffi.Int, ffi.Int)>()
external void glfwWindowHint(int hint, int value);

/// Sets the specified window hint to the desired value.
@ffi.Native<ffi.Void Function(ffi.Int, ffi.Pointer<ffi.Char>)>()
external void glfwWindowHintString(int hint, ffi.Pointer<ffi.Char> value);

/// Creates a window and its associated context.
@ffi.Native<
  ffi.Pointer<GLFWwindow> Function(
    ffi.Int,
    ffi.Int,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<GLFWmonitor>,
    ffi.Pointer<GLFWwindow>,
  )
>()
external ffi.Pointer<GLFWwindow> glfwCreateWindow(
  int width,
  int height,
  ffi.Pointer<ffi.Char> title,
  ffi.Pointer<GLFWmonitor> monitor,
  ffi.Pointer<GLFWwindow> share,
);

/// Destroys the specified window and its context.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>)>()
external void glfwDestroyWindow(ffi.Pointer<GLFWwindow> window);

/// Checks the close flag of the specified window.
@ffi.Native<ffi.Int Function(ffi.Pointer<GLFWwindow>)>()
external int glfwWindowShouldClose(ffi.Pointer<GLFWwindow> window);

/// Sets the close flag of the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Int)>()
external void glfwSetWindowShouldClose(ffi.Pointer<GLFWwindow> window, int value);

/// Returns the title of the specified window.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<GLFWwindow>)>()
external ffi.Pointer<ffi.Char> glfwGetWindowTitle(ffi.Pointer<GLFWwindow> window);

/// Sets the title of the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Pointer<ffi.Char>)>()
external void glfwSetWindowTitle(ffi.Pointer<GLFWwindow> window, ffi.Pointer<ffi.Char> title);

/// Sets the icon for the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Int, ffi.Pointer<GLFWimage>)>()
external void glfwSetWindowIcon(ffi.Pointer<GLFWwindow> window, int count, ffi.Pointer<GLFWimage> images);

/// Retrieves the position of the content area of the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external void glfwGetWindowPos(ffi.Pointer<GLFWwindow> window, ffi.Pointer<ffi.Int> xpos, ffi.Pointer<ffi.Int> ypos);

/// Sets the position of the content area of the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Int, ffi.Int)>()
external void glfwSetWindowPos(ffi.Pointer<GLFWwindow> window, int xpos, int ypos);

/// Retrieves the size of the content area of the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external void glfwGetWindowSize(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.Int> width,
  ffi.Pointer<ffi.Int> height,
);

/// Sets the size limits of the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Int, ffi.Int, ffi.Int, ffi.Int)>()
external void glfwSetWindowSizeLimits(
  ffi.Pointer<GLFWwindow> window,
  int minwidth,
  int minheight,
  int maxwidth,
  int maxheight,
);

/// Sets the aspect ratio of the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Int, ffi.Int)>()
external void glfwSetWindowAspectRatio(ffi.Pointer<GLFWwindow> window, int numer, int denom);

/// Sets the size of the content area of the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Int, ffi.Int)>()
external void glfwSetWindowSize(ffi.Pointer<GLFWwindow> window, int width, int height);

/// Retrieves the size of the framebuffer of the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Pointer<ffi.Int>, ffi.Pointer<ffi.Int>)>()
external void glfwGetFramebufferSize(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.Int> width,
  ffi.Pointer<ffi.Int> height,
);

/// Retrieves the size of the frame of the window.
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
  )
>()
external void glfwGetWindowFrameSize(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.Int> left,
  ffi.Pointer<ffi.Int> top,
  ffi.Pointer<ffi.Int> right,
  ffi.Pointer<ffi.Int> bottom,
);

/// Retrieves the content scale for the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Pointer<ffi.Float>, ffi.Pointer<ffi.Float>)>()
external void glfwGetWindowContentScale(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.Float> xscale,
  ffi.Pointer<ffi.Float> yscale,
);

/// Returns the opacity of the whole window.
@ffi.Native<ffi.Float Function(ffi.Pointer<GLFWwindow>)>()
external double glfwGetWindowOpacity(ffi.Pointer<GLFWwindow> window);

/// Sets the opacity of the whole window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Float)>()
external void glfwSetWindowOpacity(ffi.Pointer<GLFWwindow> window, double opacity);

/// Iconifies the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>)>()
external void glfwIconifyWindow(ffi.Pointer<GLFWwindow> window);

/// Restores the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>)>()
external void glfwRestoreWindow(ffi.Pointer<GLFWwindow> window);

/// Maximizes the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>)>()
external void glfwMaximizeWindow(ffi.Pointer<GLFWwindow> window);

/// Makes the specified window visible.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>)>()
external void glfwShowWindow(ffi.Pointer<GLFWwindow> window);

/// Hides the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>)>()
external void glfwHideWindow(ffi.Pointer<GLFWwindow> window);

/// Brings the specified window to front and sets input focus.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>)>()
external void glfwFocusWindow(ffi.Pointer<GLFWwindow> window);

/// Requests user attention to the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>)>()
external void glfwRequestWindowAttention(ffi.Pointer<GLFWwindow> window);

/// Returns the monitor that the window uses for full screen mode.
@ffi.Native<ffi.Pointer<GLFWmonitor> Function(ffi.Pointer<GLFWwindow>)>()
external ffi.Pointer<GLFWmonitor> glfwGetWindowMonitor(ffi.Pointer<GLFWwindow> window);

/// Sets the mode, monitor, video mode and placement of a window.
@ffi.Native<
  ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Pointer<GLFWmonitor>, ffi.Int, ffi.Int, ffi.Int, ffi.Int, ffi.Int)
>()
external void glfwSetWindowMonitor(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<GLFWmonitor> monitor,
  int xpos,
  int ypos,
  int width,
  int height,
  int refreshRate,
);

/// Returns an attribute of the specified window.
@ffi.Native<ffi.Int Function(ffi.Pointer<GLFWwindow>, ffi.Int)>()
external int glfwGetWindowAttrib(ffi.Pointer<GLFWwindow> window, int attrib);

/// Sets an attribute of the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Int, ffi.Int)>()
external void glfwSetWindowAttrib(ffi.Pointer<GLFWwindow> window, int attrib, int value);

/// Sets the user pointer of the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Pointer<ffi.Void>)>()
external void glfwSetWindowUserPointer(ffi.Pointer<GLFWwindow> window, ffi.Pointer<ffi.Void> pointer);

/// Returns the user pointer of the specified window.
@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<GLFWwindow>)>()
external ffi.Pointer<ffi.Void> glfwGetWindowUserPointer(ffi.Pointer<GLFWwindow> window);

/// Sets the position callback for the specified window.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int xpos, ffi.Int ypos)>>
  Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int xpos, ffi.Int ypos)>>,
  )
>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int xpos, ffi.Int ypos)>>
glfwSetWindowPosCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int xpos, ffi.Int ypos)>>
  callback,
);

/// Sets the size callback for the specified window.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int width, ffi.Int height)>>
  Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int width, ffi.Int height)>>,
  )
>()
external ffi.Pointer<
  ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int width, ffi.Int height)>
>
glfwSetWindowSizeCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int width, ffi.Int height)>>
  callback,
);

/// Sets the close callback for the specified window.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window)>> Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window)>>,
  )
>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window)>> glfwSetWindowCloseCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window)>> callback,
);

/// Sets the refresh callback for the specified window.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window)>> Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window)>>,
  )
>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window)>>
glfwSetWindowRefreshCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window)>> callback,
);

/// Sets the focus callback for the specified window.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int focused)>> Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int focused)>>,
  )
>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int focused)>>
glfwSetWindowFocusCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int focused)>> callback,
);

/// Sets the iconify callback for the specified window.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int iconified)>> Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int iconified)>>,
  )
>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int iconified)>>
glfwSetWindowIconifyCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int iconified)>> callback,
);

/// Sets the maximize callback for the specified window.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int maximized)>> Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int maximized)>>,
  )
>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int maximized)>>
glfwSetWindowMaximizeCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int maximized)>> callback,
);

/// Sets the framebuffer resize callback for the specified window.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int width, ffi.Int height)>>
  Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int width, ffi.Int height)>>,
  )
>()
external ffi.Pointer<
  ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int width, ffi.Int height)>
>
glfwSetFramebufferSizeCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int width, ffi.Int height)>>
  callback,
);

/// Sets the window content scale callback for the specified window.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Float xscale, ffi.Float yscale)>>
  Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Float xscale, ffi.Float yscale)>
    >,
  )
>()
external ffi.Pointer<
  ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Float xscale, ffi.Float yscale)>
>
glfwSetWindowContentScaleCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Float xscale, ffi.Float yscale)>>
  callback,
);

/// Processes all pending events.
@ffi.Native<ffi.Void Function()>()
external void glfwPollEvents();

/// Waits until events are queued and processes them.
@ffi.Native<ffi.Void Function()>()
external void glfwWaitEvents();

/// Waits with timeout until events are queued and processes them.
@ffi.Native<ffi.Void Function(ffi.Double)>()
external void glfwWaitEventsTimeout(double timeout);

/// Posts an empty event to the event queue.
@ffi.Native<ffi.Void Function()>()
external void glfwPostEmptyEvent();

/// Returns the value of an input option for the specified window.
@ffi.Native<ffi.Int Function(ffi.Pointer<GLFWwindow>, ffi.Int)>()
external int glfwGetInputMode(ffi.Pointer<GLFWwindow> window, int mode);

/// Sets an input option for the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Int, ffi.Int)>()
external void glfwSetInputMode(ffi.Pointer<GLFWwindow> window, int mode, int value);

/// Returns whether raw mouse motion is supported.
@ffi.Native<ffi.Int Function()>()
external int glfwRawMouseMotionSupported();

/// Returns the layout-specific name of the specified printable key.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int, ffi.Int)>()
external ffi.Pointer<ffi.Char> glfwGetKeyName(int key, int scancode);

/// Returns the platform-specific scancode of the specified key.
@ffi.Native<ffi.Int Function(ffi.Int)>()
external int glfwGetKeyScancode(int key);

/// Returns the last reported state of a keyboard key for the specified
/// window.
@ffi.Native<ffi.Int Function(ffi.Pointer<GLFWwindow>, ffi.Int)>()
external int glfwGetKey(ffi.Pointer<GLFWwindow> window, int key);

/// Returns the last reported state of a mouse button for the specified
/// window.
@ffi.Native<ffi.Int Function(ffi.Pointer<GLFWwindow>, ffi.Int)>()
external int glfwGetMouseButton(ffi.Pointer<GLFWwindow> window, int button);

/// Retrieves the position of the cursor relative to the content area of the
/// window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Pointer<ffi.Double>, ffi.Pointer<ffi.Double>)>()
external void glfwGetCursorPos(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.Double> xpos,
  ffi.Pointer<ffi.Double> ypos,
);

/// Sets the position of the cursor, relative to the content area of the
/// window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Double, ffi.Double)>()
external void glfwSetCursorPos(ffi.Pointer<GLFWwindow> window, double xpos, double ypos);

/// Creates a custom cursor.
@ffi.Native<ffi.Pointer<GLFWcursor> Function(ffi.Pointer<GLFWimage>, ffi.Int, ffi.Int)>()
external ffi.Pointer<GLFWcursor> glfwCreateCursor(ffi.Pointer<GLFWimage> image, int xhot, int yhot);

/// Creates a cursor with a standard shape.
@ffi.Native<ffi.Pointer<GLFWcursor> Function(ffi.Int)>()
external ffi.Pointer<GLFWcursor> glfwCreateStandardCursor(int shape);

/// Destroys a cursor.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWcursor>)>()
external void glfwDestroyCursor(ffi.Pointer<GLFWcursor> cursor);

/// Sets the cursor for the window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Pointer<GLFWcursor>)>()
external void glfwSetCursor(ffi.Pointer<GLFWwindow> window, ffi.Pointer<GLFWcursor> cursor);

/// Sets the key callback.
@ffi.Native<
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int key, ffi.Int scancode, ffi.Int action, ffi.Int mods)
    >
  >
  Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int key, ffi.Int scancode, ffi.Int action, ffi.Int mods)
      >
    >,
  )
>()
external ffi.Pointer<
  ffi.NativeFunction<
    ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int key, ffi.Int scancode, ffi.Int action, ffi.Int mods)
  >
>
glfwSetKeyCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int key, ffi.Int scancode, ffi.Int action, ffi.Int mods)
    >
  >
  callback,
);

/// Sets the Unicode character callback.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.UnsignedInt codepoint)>>
  Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.UnsignedInt codepoint)>>,
  )
>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.UnsignedInt codepoint)>>
glfwSetCharCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.UnsignedInt codepoint)>>
  callback,
);

/// Sets the Unicode character with modifiers callback.
@ffi.Native<
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.UnsignedInt codepoint, ffi.Int mods)>
  >
  Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.UnsignedInt codepoint, ffi.Int mods)>
    >,
  )
>()
external ffi.Pointer<
  ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.UnsignedInt codepoint, ffi.Int mods)>
>
glfwSetCharModsCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.UnsignedInt codepoint, ffi.Int mods)>
  >
  callback,
);

/// Sets the mouse button callback.
@ffi.Native<
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int button, ffi.Int action, ffi.Int mods)>
  >
  Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int button, ffi.Int action, ffi.Int mods)
      >
    >,
  )
>()
external ffi.Pointer<
  ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int button, ffi.Int action, ffi.Int mods)>
>
glfwSetMouseButtonCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int button, ffi.Int action, ffi.Int mods)>
  >
  callback,
);

/// Sets the cursor position callback.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Double xpos, ffi.Double ypos)>>
  Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Double xpos, ffi.Double ypos)>
    >,
  )
>()
external ffi.Pointer<
  ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Double xpos, ffi.Double ypos)>
>
glfwSetCursorPosCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Double xpos, ffi.Double ypos)>>
  callback,
);

/// Sets the cursor enter/leave callback.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int entered)>> Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int entered)>>,
  )
>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int entered)>>
glfwSetCursorEnterCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int entered)>> callback,
);

/// Sets the scroll callback.
@ffi.Native<
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Double xoffset, ffi.Double yoffset)>
  >
  Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Double xoffset, ffi.Double yoffset)>
    >,
  )
>()
external ffi.Pointer<
  ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Double xoffset, ffi.Double yoffset)>
>
glfwSetScrollCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Double xoffset, ffi.Double yoffset)>
  >
  callback,
);

/// Sets the path drop callback.
@ffi.Native<
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int path_count, ffi.Pointer<ffi.Pointer<ffi.Char>> paths)
    >
  >
  Function(
    ffi.Pointer<GLFWwindow>,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int path_count, ffi.Pointer<ffi.Pointer<ffi.Char>> paths)
      >
    >,
  )
>()
external ffi.Pointer<
  ffi.NativeFunction<
    ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int path_count, ffi.Pointer<ffi.Pointer<ffi.Char>> paths)
  >
>
glfwSetDropCallback(
  ffi.Pointer<GLFWwindow> window,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<GLFWwindow> window, ffi.Int path_count, ffi.Pointer<ffi.Pointer<ffi.Char>> paths)
    >
  >
  callback,
);

/// Returns whether the specified joystick is present.
@ffi.Native<ffi.Int Function(ffi.Int)>()
external int glfwJoystickPresent(int jid);

/// Returns the values of all axes of the specified joystick.
@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Int, ffi.Pointer<ffi.Int>)>()
external ffi.Pointer<ffi.Float> glfwGetJoystickAxes(int jid, ffi.Pointer<ffi.Int> count);

/// Returns the state of all buttons of the specified joystick.
@ffi.Native<ffi.Pointer<ffi.UnsignedChar> Function(ffi.Int, ffi.Pointer<ffi.Int>)>()
external ffi.Pointer<ffi.UnsignedChar> glfwGetJoystickButtons(int jid, ffi.Pointer<ffi.Int> count);

/// Returns the state of all hats of the specified joystick.
@ffi.Native<ffi.Pointer<ffi.UnsignedChar> Function(ffi.Int, ffi.Pointer<ffi.Int>)>()
external ffi.Pointer<ffi.UnsignedChar> glfwGetJoystickHats(int jid, ffi.Pointer<ffi.Int> count);

/// Returns the name of the specified joystick.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>()
external ffi.Pointer<ffi.Char> glfwGetJoystickName(int jid);

/// Returns the SDL compatible GUID of the specified joystick.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>()
external ffi.Pointer<ffi.Char> glfwGetJoystickGUID(int jid);

/// Sets the user pointer of the specified joystick.
@ffi.Native<ffi.Void Function(ffi.Int, ffi.Pointer<ffi.Void>)>()
external void glfwSetJoystickUserPointer(int jid, ffi.Pointer<ffi.Void> pointer);

/// Returns the user pointer of the specified joystick.
@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Int)>()
external ffi.Pointer<ffi.Void> glfwGetJoystickUserPointer(int jid);

/// Returns whether the specified joystick has a gamepad mapping.
@ffi.Native<ffi.Int Function(ffi.Int)>()
external int glfwJoystickIsGamepad(int jid);

/// Sets the joystick configuration callback.
@ffi.Native<
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int jid, ffi.Int event)>> Function(
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int jid, ffi.Int event)>>,
  )
>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int jid, ffi.Int event)>> glfwSetJoystickCallback(
  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int jid, ffi.Int event)>> callback,
);

/// Adds the specified SDL_GameControllerDB gamepad mappings.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int glfwUpdateGamepadMappings(ffi.Pointer<ffi.Char> string);

/// Returns the human-readable gamepad name for the specified joystick.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>()
external ffi.Pointer<ffi.Char> glfwGetGamepadName(int jid);

/// Retrieves the state of the specified joystick remapped as a gamepad.
@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<GLFWgamepadstate>)>()
external int glfwGetGamepadState(int jid, ffi.Pointer<GLFWgamepadstate> state);

/// Sets the clipboard to the specified string.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>, ffi.Pointer<ffi.Char>)>()
external void glfwSetClipboardString(ffi.Pointer<GLFWwindow> window, ffi.Pointer<ffi.Char> string);

/// Returns the contents of the clipboard as a string.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<GLFWwindow>)>()
external ffi.Pointer<ffi.Char> glfwGetClipboardString(ffi.Pointer<GLFWwindow> window);

/// Returns the GLFW time.
@ffi.Native<ffi.Double Function()>()
external double glfwGetTime();

/// Sets the GLFW time.
@ffi.Native<ffi.Void Function(ffi.Double)>()
external void glfwSetTime(double time);

/// Returns the current value of the raw timer.
@ffi.Native<ffi.Uint64 Function()>()
external int glfwGetTimerValue();

/// Returns the frequency, in Hz, of the raw timer.
@ffi.Native<ffi.Uint64 Function()>()
external int glfwGetTimerFrequency();

/// Makes the context of the specified window current for the calling thread.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>)>()
external void glfwMakeContextCurrent(ffi.Pointer<GLFWwindow> window);

/// Returns the window whose context is current on the calling thread.
@ffi.Native<ffi.Pointer<GLFWwindow> Function()>()
external ffi.Pointer<GLFWwindow> glfwGetCurrentContext();

/// Swaps the front and back buffers of the specified window.
@ffi.Native<ffi.Void Function(ffi.Pointer<GLFWwindow>)>()
external void glfwSwapBuffers(ffi.Pointer<GLFWwindow> window);

/// Sets the swap interval for the current context.
@ffi.Native<ffi.Void Function(ffi.Int)>()
external void glfwSwapInterval(int interval);

/// Returns whether the specified extension is available.
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int glfwExtensionSupported(ffi.Pointer<ffi.Char> extension);

/// Returns the address of the specified function for the current context.
@ffi.Native<ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> glfwGetProcAddress(ffi.Pointer<ffi.Char> procname);

/// Returns whether the Vulkan loader and an ICD have been found.
@ffi.Native<ffi.Int Function()>()
external int glfwVulkanSupported();

/// Returns the Vulkan instance extensions required by GLFW.
@ffi.Native<ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<ffi.Uint32>)>()
external ffi.Pointer<ffi.Pointer<ffi.Char>> glfwGetRequiredInstanceExtensions(ffi.Pointer<ffi.Uint32> count);

final class GLFWmonitor extends ffi.Opaque {}

final class GLFWwindow extends ffi.Opaque {}

final class GLFWcursor extends ffi.Opaque {}

/// Video mode type.
final class GLFWvidmode extends ffi.Struct {
  /// The width, in screen coordinates, of the video mode.
  @ffi.Int()
  external int width;

  /// The height, in screen coordinates, of the video mode.
  @ffi.Int()
  external int height;

  /// The bit depth of the red channel of the video mode.
  @ffi.Int()
  external int redBits;

  /// The bit depth of the green channel of the video mode.
  @ffi.Int()
  external int greenBits;

  /// The bit depth of the blue channel of the video mode.
  @ffi.Int()
  external int blueBits;

  /// The refresh rate, in Hz, of the video mode.
  @ffi.Int()
  external int refreshRate;
}

/// Gamma ramp.
final class GLFWgammaramp extends ffi.Struct {
  /// An array of value describing the response of the red channel.
  external ffi.Pointer<ffi.UnsignedShort> red;

  /// An array of value describing the response of the green channel.
  external ffi.Pointer<ffi.UnsignedShort> green;

  /// An array of value describing the response of the blue channel.
  external ffi.Pointer<ffi.UnsignedShort> blue;

  /// The number of elements in each array.
  @ffi.UnsignedInt()
  external int size;
}

/// Image data.
final class GLFWimage extends ffi.Struct {
  /// The width, in pixels, of this image.
  @ffi.Int()
  external int width;

  /// The height, in pixels, of this image.
  @ffi.Int()
  external int height;

  /// The pixel data of this image, arranged left-to-right, top-to-bottom.
  external ffi.Pointer<ffi.UnsignedChar> pixels;
}

/// Gamepad input state
final class GLFWgamepadstate extends ffi.Struct {
  /// The states of each [gamepad button]( gamepad_buttons), `glfwPress` or
  /// `glfwRelease`.
  @ffi.Array.multi([15])
  external ffi.Array<ffi.UnsignedChar> buttons;

  /// The states of each [gamepad axis]( gamepad_axes), in the range -1.0 to 1.0
  /// inclusive.
  @ffi.Array.multi([6])
  external ffi.Array<ffi.Float> axes;
}

/// Custom heap memory allocator.
final class GLFWallocator extends ffi.Struct {
  /// The memory allocation function. See GLFWallocatefun for details about
  /// allocation function.
  external ffi.Pointer<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size size, ffi.Pointer<ffi.Void> user)>>
  allocate;

  /// The memory reallocation function. See GLFWreallocatefun for details about
  /// reallocation function.
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void> block, ffi.Size size, ffi.Pointer<ffi.Void> user)
    >
  >
  reallocate;

  /// The memory deallocation function. See GLFWdeallocatefun for details about
  /// deallocation function.
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> block, ffi.Pointer<ffi.Void> user)>>
  deallocate;

  /// The user pointer for this custom allocator. This value will be passed to
  /// the allocator functions.
  external ffi.Pointer<ffi.Void> user;
}
